AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ReceiptSense – serverless receipt OCR & expense storage

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512

Resources:

  ReceiptsBucket:
    Type: AWS::S3::Bucket

  ProcessReceiptFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      CodeUri: src/
      Policies:
        - Statement:                   
          - Effect: Allow
            Action: s3:GetObject
            Resource: "*"
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpensesTable
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - textract:AnalyzeExpense
              Resource: "*"
        - Statement:
          - Effect: Allow
            Action: bedrock:InvokeModel
            Resource: "*"
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpensesTable
      Events:
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref ReceiptsBucket
            Events: s3:ObjectCreated:*       
            Filter:                          
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jpg

  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ReceiptId
          AttributeType: S
        - AttributeName: Vendor          
          AttributeType: S
        - AttributeName: TxDate          
          AttributeType: S
        - AttributeName: VendorNorm
          AttributeType: S
        - AttributeName: Category
          AttributeType: S
      KeySchema:
        - AttributeName: ReceiptId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:          
        - IndexName: VendorIndex
          KeySchema:
            - AttributeName: Vendor
              KeyType: HASH
          Projection: { ProjectionType: ALL }
        - IndexName: DateIndex
          KeySchema:
            - AttributeName: TxDate
              KeyType: HASH
          Projection: { ProjectionType: ALL }
        - IndexName: VendorNormIndex
          KeySchema:
            - AttributeName: VendorNorm
              KeyType: HASH
          Projection: {ProjectionType: ALL}
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: Category
              KeyType: HASH
          Projection: {ProjectionType: ALL}

  ExpensesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,DELETE,OPTIONS'"

  QueryExpensesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: query.handler
      CodeUri: src/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ExpensesTable
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpensesTable
      Events:
        GetExpenses:
          Type: Api
          Properties:
            RestApiId: !Ref ExpensesApi
            Path: /expenses
            Method: get
  
  PresignFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: presign.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3WritePolicy:
            BucketName: !Ref ReceiptsBucket
      Environment:
        Variables:
          BUCKET: !Ref ReceiptsBucket
      Events:
        PostUpload:
          Type: Api
          Properties:
            RestApiId: !Ref ExpensesApi
            Path: /upload
            Method: post
        CorsPreflight:
          Type: Api
          Properties:
            RestApiId: !Ref ExpensesApi
            Path: /upload
            Method: options
  
  ExportCSVFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: export_csv.handler
      Runtime: python3.12
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ExpensesTable
        - S3WritePolicy:
            BucketName: !Ref ReceiptsBucket   
        - S3ReadPolicy:           
            BucketName: !Ref ReceiptsBucket
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          TABLE_NAME:  !Ref ExpensesTable
          BUCKET_NAME: !Ref ReceiptsBucket
      Events:
        Export:
          Type: Api
          Properties:
            RestApiId: !Ref ExpensesApi
            Path: /export
            Method: get

  DeleteReceiptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: delete_receipt.handler
      Runtime: python3.12
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpensesTable
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          TABLE_NAME: !Ref ExpensesTable
      Events:
        Delete:
          Type: Api
          Properties:
            RestApiId: !Ref ExpensesApi
            Path: /expenses/{rid}
            Method: delete
